#  hostname or IP in dotted decimal form of the sensor
sensor_hostname: 192.168.1.12

#  hostname or IP where the sensor will send data packets
udp_dest: 192.168.1.100

#  port to which the sensor should send lidar data
lidar_port: 7502

#  port to which the sensor should send imu data
imu_port: 7503

#  do not connect to a sensor; expect /os_node/{lidar,imu}_packets from replay
replay: false

#  resolution and rate: either 512x10, 512x20, 1024x10, 1024x20, or 2048x10
lidar_mode: 2048x10

#  method used to timestamp measurements: TIME_FROM_INTERNAL_OSC, TIME_FROM_SYNC_PULSE_IN, TIME_FROM_PTP_1588
timestamp_mode: TIME_FROM_PTP_1588

#  lidar packet profile: LEGACY, RNG19_RFL8_SIG16_NIR16_DUAL, RNG19_RFL8_SIG16_NIR16, RNG15_RFL8_NIR8
udp_profile_lidar: RNG15_RFL8_NIR8

#  namespace for tf transforms
tf_prefix: vert
